#!/bin/sh

usage()
{
    cat <<EOF
Usage: audiere-config [OPTIONS]
Options:
        [--prefix]
        [--version]
        [--cxxflags]
        [--libs]
EOF
    exit $1
}

if test $# -eq 0; then
    usage 1 1>&2
fi

while test $# -gt 0; do
    case "$1" in
        -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
        *) optarg= ;;
    esac

    case $1 in
        --prefix)
            echo /c/mingw
            ;;
        --version)
            echo 1.9.5
            ;;
        --cxxflags)
            echo -I/c/mingw${prefix}/include
            ;;
        --libs)
            echo -L/c/mingw${exec_prefix}/lib -laudiere -lwinmm -ldsound -lole32 -lrpcrt4 -lvorbisfile -lvorbis -logg -lpthread 
            ;;
        *)
            usage 1 1>& 2
            ;;
    esac
    shift
done
